# Generated by Django 4.0.3 on 2022-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_numurs', models.IntegerField()),
                ('amount', models.FloatField()),
                ('due_to_date', models.DateField()),
            ],
        ),
    ]
