# Generated by Django 4.0.3 on 2022-03-21 16:56

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_numurs',
            field=models.TextField(unique=True, validators=[api.validators.val_num]),
        ),
    ]
