# Generated by Django 4.0.3 on 2022-03-28 07:27

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_period',
            field=models.TextField(validators=[api.validators.val_period]),
        ),
    ]
