# Generated by Django 4.0.3 on 2022-04-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invoice_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_period',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_period_month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_period_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
