# Generated by Django 4.0.3 on 2022-04-04 11:48

import api.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_invoice_payment_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='access_path',
            field=models.FilePathField(default=models.TextField(unique=True, validators=[api.validators.val_num]), path=pathlib.PureWindowsPath('C:/repos/AIB/AIB/agreements')),
        ),
    ]
