# Generated by Django 4.0.3 on 2022-04-04 12:21

import api.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_agreement_access_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='access_path',
            field=models.FilePathField(default=models.TextField(unique=True, validators=[api.validators.val_num]), path=pathlib.PureWindowsPath('C:/repos/AIB/AIB/agreements')),
        ),
    ]
