# Generated by Django 4.0.3 on 2022-04-04 12:27

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_agreement_access_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='access_path',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/repos/AIB/AIB/agreements')),
        ),
    ]
