# Generated by Django 4.0.3 on 2022-04-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_agreement_access_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='access_path',
            new_name='document_file',
        ),
    ]
