# Generated by Django 4.0.3 on 2022-04-04 12:41

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_access_path_agreement_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='document_file',
            field=models.FileField(blank=True, upload_to=pathlib.PureWindowsPath('C:/repos/AIB/AIB/agreements')),
        ),
    ]
