# Generated by Django 4.0.3 on 2022-05-02 01:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_invoice_payment_period_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=api.models.nameFile)),
            ],
        ),
    ]
