# Generated by Django 4.0.3 on 2022-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_invoice_payment_period_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.TextField(default='John Smith'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('ON', 'Online'), ('DEL', 'Cash on delivery'), ('CSH', 'Cash before delivery')], default='ON', max_length=3),
        ),
    ]