# Generated by Django 4.0.3 on 2022-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.TextField(default='pending sign off'),
        ),
    ]
