# Generated by Django 4.0.3 on 2022-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_agreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='customer',
            field=models.TextField(default='John Smith'),
        ),
    ]
