# Generated by Django 4.0.3 on 2022-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_agreement_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='customer',
            field=models.TextField(),
        ),
    ]
