# Generated by Django 4.0.3 on 2022-05-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_agreement_owner_invoice_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.TextField(choices=[('By agreement', 'By Agr'), ('regular invoice', 'Regular'), ('accrual invoce', 'Accrual')], default='regular invoice'),
        ),
    ]
