# Generated by Django 4.0.3 on 2022-06-01 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.TextField(choices=[('pending sign off', 'Pending'), ('draft', 'Draft'), ('signed', 'Signed')], default='draft'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.TextField(choices=[('by agreement', 'By Agr'), ('regular invoice', 'Regular'), ('accrual invoice', 'Accrual')], default='regular invoice'),
        ),
    ]
