# Generated by Django 4.0.3 on 2022-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.TextField(choices=[('pending sign off', 'Pending'), ('draft', 'Draft'), ('signed', 'Signed')], default='draft'),
        ),
    ]
