# Generated by Django 4.0.3 on 2022-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.TextField(choices=[('By agreement', 'By Agr'), ('regular invoice', 'Regular'), ('accrual invoice', 'Accrual')], default='regular invoice'),
        ),
    ]
